{% set name = "smif" %}
{% set version = "1.0.1" %}
{% set sha256 = "05c9ddbe70005b45cef6ab72b1fe71e4a9acc464de519c84d1e659a7590cd007" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . -vv
  noarch: python
  entry_points:
    - smif = smif.cli:main

requirements:
  build:
    - python >=3.5
    - setuptools >=30.3.0
    - six
    - pyscaffold >=3.0
  host:
    - pip
  run:
    - python >=3.5
    - fiona >=1.7.13
    - gdal >=2.2.4
    - libgdal >=2.2.4
    - flask >=0.12
    - isodate >=0.6
    - networkx >=1.11
    - numpy >=1.10
    - pandas
    - pint >=0.8
    - pyarrow >=0.8
    - python
    - python-dateutil >=2.6
    - rtree >=0.7
    - ruamel.yaml
    - scikit-optimize >=0.3
    - shapely >=1.3
    - xarray


test:
  imports:
    - smif
    - smif.cli
    - smif.convert
    - smif.data_layer
    - smif.http_api
    - smif.model
    - smif.parameters
  commands:
    - smif -h

about:
  home: http://github.com/nismod/smif
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Simulation Modelling Integration Framework'
  description: |
    smif is a framework for handling the creation of system-of-systems models.
    The framework handles inputs and outputs, dependencies between models,
    persistence of data and the communication of state across years. This early
    version of the framework handles simulation models that simulate the
    operation of a system within a year. smif exposes an interface to a planning
    module which will allows different algorithms to be used against a common
    API.
  doc_url: http://smif.readthedocs.io/
  dev_url: https://github.com/nismod/smif

extra:
  recipe-maintainers:
    - tomalrussell
    - willu47
