{% set name = "smif" %}
{% set version = "1.3.2.post2" %}
{% set sha256 = "ec2a499e3ac836626ca92d8bc37a0f39acf3490275591797b939ac94e4a3bb1d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . -vv
  noarch: python
  entry_points:
    - smif = smif.cli:main

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools >=30.3.0
    - six
    - pyscaffold >=3.0a0,<3.1a0
    - fiona >=1.7
    - flask >=0.12
    - gdal >=2.2.4
    - isodate >=0.6
    - libgdal >=2.2.4
    - minio
    - networkx >=1.11
    - numpy >=1.11
    - pandas
    - pint >=0.8
    - pyarrow >=0.9
    - python-dateutil >=2.6
    - requests
    - rtree >=0.7
    - ruamel.yaml >=0.15.50
    - shapely >=1.3
    - xarray
  run:
    - python >=3.5
    - fiona >=1.7
    - flask >=0.12
    - gdal >=2.2.4
    - isodate >=0.6
    - libgdal >=2.2.4
    - minio
    - networkx >=1.11
    - numpy >=1.11
    - pandas
    - pint >=0.8
    - pyarrow >=0.9
    - python-dateutil >=2.6
    - requests
    - rtree >=0.7
    - ruamel.yaml >=0.15.50
    - shapely >=1.3
    - xarray


test:
  imports:
    - smif
    - smif.cli
    - smif.controller
    - smif.controller.job
    - smif.controller.run
    - smif.convert
    - smif.data_layer
    - smif.data_layer.file
    - smif.decision
    - smif.http_api
    - smif.metadata
    - smif.model
  commands:
    - smif -h

about:
  home: http://github.com/nismod/smif
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simulation Modelling Integration Framework
  description: |
    smif is a framework for handling the creation of system-of-systems models.
    The framework handles inputs and outputs, dependencies between models,
    persistence of data and the communication of state across years. This
    version of the framework handles simulation models that simulate the
    operation of a system within a year. smif exposes an interface to a planning
    module which allows different algorithms to be used against a common API.
  doc_url: http://smif.readthedocs.io/
  dev_url: https://github.com/nismod/smif

extra:
  recipe-maintainers:
    - tomalrussell
    - willu47
