# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RDrVbioXtzqwCuZd/huAyL0xq9kOE9VkSn57VYhSKJdhm7C78BMTTnOtObGqPFTrPHwi5AwuM/UzvkcdoPue3SoRt/ysnYkufFsPlurFNOoJ4DXb3ib5ddMud5AENGw8c0psXcbbVEeMAF3ZysalN1PjycNKp4pHxep5GX2BFE8RaKbeT5ej+B6BlFwn21rJz9hgEETZrsyht3GZ30t0PWrz3K9MHHLNleqPpPD0dX/DVt4TmYAF7Rdnvd5rJtsWWfjfpIUi4mbNeCmiWgpNT2QfHHmh4u8OwkXMVolS+8tyDn/yr/xGUaJnrmURBaslDBKXAcHiuOHIgCaPgscHEcGWGHSunDWCmHoxMEdU33wO2cBuUzqn9nqNPaNx6dsdatOn6vNIVVuvJjSl7AR5xa60HqY1T3v4N8QjNTYKG3E5K3XOIiqKcLAhzI/TKaOfr2PxC3EGOBGJu0mV2+1T8l8iwtyDC2lh5hahsT5mKQDZHQgiGAqZmPlwH9aO/KLLgF30LUJeBR9O50v8J+AGDjpQ9U4/U+5EzNFnadT3tjgobRCRhdGc0ZBlgzh9kuXOfby1dH52tvL13k8g74OD1WVKtX/CfDLKs3/zRFhKzJgW+VBQ5TiuBRNj5h6F6hLjqDYqpjvwlDrDg8IPdxLyK9UB49Iis28FmGiQkAEy3UE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
