travis:
  secure:
    BINSTAR_TOKEN: RDrVbioXtzqwCuZd/huAyL0xq9kOE9VkSn57VYhSKJdhm7C78BMTTnOtObGqPFTrPHwi5AwuM/UzvkcdoPue3SoRt/ysnYkufFsPlurFNOoJ4DXb3ib5ddMud5AENGw8c0psXcbbVEeMAF3ZysalN1PjycNKp4pHxep5GX2BFE8RaKbeT5ej+B6BlFwn21rJz9hgEETZrsyht3GZ30t0PWrz3K9MHHLNleqPpPD0dX/DVt4TmYAF7Rdnvd5rJtsWWfjfpIUi4mbNeCmiWgpNT2QfHHmh4u8OwkXMVolS+8tyDn/yr/xGUaJnrmURBaslDBKXAcHiuOHIgCaPgscHEcGWGHSunDWCmHoxMEdU33wO2cBuUzqn9nqNPaNx6dsdatOn6vNIVVuvJjSl7AR5xa60HqY1T3v4N8QjNTYKG3E5K3XOIiqKcLAhzI/TKaOfr2PxC3EGOBGJu0mV2+1T8l8iwtyDC2lh5hahsT5mKQDZHQgiGAqZmPlwH9aO/KLLgF30LUJeBR9O50v8J+AGDjpQ9U4/U+5EzNFnadT3tjgobRCRhdGc0ZBlgzh9kuXOfby1dH52tvL13k8g74OD1WVKtX/CfDLKs3/zRFhKzJgW+VBQ5TiuBRNj5h6F6hLjqDYqpjvwlDrDg8IPdxLyK9UB49Iis28FmGiQkAEy3UE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
