travis:
  secure:
    BINSTAR_TOKEN: PgM27Auxj4dYMfuocZBEYMRKoad48QByOimLsOw9lfxveXrujJWLlfUN0yDMJNLPV56oXedPx8lV4YQUd7Fb8OvJQufxJCmVqaBi+8jyR9sMMzPtKs7L8+D/zp1DHgRwK4Uja01/jwWSprWxUNMhyDUVASmBIfADNM2radVNfI09FYdyyNXbNGGh9kwSwOqoiLyKHsqIvKvCyLslH9C1LbzHf3/stSNIXF/t//MT5TxdjnYWSq39SpiHKOzSMhOkn66kNvnkfb6oZ1G3mxyJko3ew7kfaJBF4nbdTsk9/iGKylMk3gubc/LAj4tHnAxIgHcPKYcNQcfxUJFPLv5v9bgZJdj4hpHcHs98feRpWXjp7uExU/nVVsDjJq/OqWjhvMNDpa+Kfossh+jnJimbxb4gS6587X5oDxQZhpVlRwHUIJmvNsM+Tnwr4HU4Ni+BRpNua3Iupujrf0nSOjuh8pT0f+RsD1051WVu1Wms0OVPUSyvKTzR/LUKxVZN7PMzZ3d4xmKHY76q/bTx9xKet/c/YhwZ5nFvh1hM7NhLWyZOkwSu4r6SpVQ/J8Jb2NArviRPsRPG4Qg5Dop8viBiEXW7OwmZSZRSDtu+aBsWcHOLCFk9pQJGtz+81tGNktv7WNpL/HFEn330FGglB/hDpRve9AmhW0PbLsL35I7923o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
